config/routes.rb
Rails.application.routes.draw do
  resources :autocomplete_things
  resources :authors
  resources :dynamic_things
  resources :things
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/thing.rb
class Thing < ApplicationRecord
end

app/controllers/things_controller.rb
class ThingsController < ApplicationController
  before_action :set_thing, only: %i[ show edit update destroy ]

  # GET /things or /things.json
  def index
    @things = Thing.all
  end

  # GET /things/1 or /things/1.json
  def show
  end

  # GET /things/new
  def new
    @thing = Thing.new
  end

  # GET /things/1/edit
  def edit
  end

  # POST /things or /things.json
  def create
    @thing = Thing.new(thing_params)

    respond_to do |format|
      if @thing.save
        format.html { redirect_to thing_url(@thing), notice: "Thing was successfully created." }
        format.json { render :show, status: :created, location: @thing }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /things/1 or /things/1.json
  def update
    respond_to do |format|
      if @thing.update(thing_params)
        format.html { redirect_to thing_url(@thing), notice: "Thing was successfully updated." }
        format.json { render :show, status: :ok, location: @thing }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /things/1 or /things/1.json
  def destroy
    @thing.destroy

    respond_to do |format|
      format.html { redirect_to things_url, notice: "Thing was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_thing
      @thing = Thing.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def thing_params
      params.require(:thing).permit(:name, :active, :expiration_date)
    end
end

app/helpers/things_helper.rb
module ThingsHelper
end

app/views/things/_form.html.erb
<div data-controller="datepicker">
<%= form_with(model: thing) do |form| %>
  <% if thing.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(thing.errors.count, "error") %> prohibited this thing from being saved:</h2>

      <ul>
        <% thing.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :active, style: "display: block" %>
    <%= form.check_box :active %>
  </div>

  <div>
    <%= form.label :expiration_date, style: "display: block" %>
    <%= form.text_field :expiration_date, provide: "datepicker", class: "date" %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/things/_thing.html.erb
<div id="<%= dom_id thing %>">
  <p>
    <strong>Name:</strong>
    <%= thing.name %>
  </p>

  <p>
    <strong>Active:</strong>
    <%= thing.active %>
  </p>

  <p>
    <strong>Expiration date:</strong>
    <%= thing.expiration_date %>
  </p>

</div>

app/views/things/edit.html.erb
<h1>Editing thing</h1>

<%= render "form", thing: @thing %>

<br>

<div>
  <%= link_to "Show this thing", @thing %> |
  <%= link_to "Back to things", things_path %>
</div>

app/views/things/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Things</h1>

<div id="things">
  <% @things.each do |thing| %>
    <%= render thing %>
    <p>
      <%= link_to "Show this thing", thing %>
    </p>
  <% end %>
</div>

<div data-controller="toggle">
    <button data-action="toggle#do_toggle">Hide/Show</button>
    <p class="hide_show">
      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna
      aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
      Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint
      occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    </p>
</div>

<%= link_to "New thing", new_thing_path %>

app/views/things/new.html.erb
<h1>New thing</h1>

<%= render "form", thing: @thing %>

<br>

<div>
  <%= link_to "Back to things", things_path %>
</div>

app/views/things/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @thing %>

<div>
  <%= link_to "Edit this thing", edit_thing_path(@thing) %> |
  <%= link_to "Back to things", things_path %>

  <%= button_to "Destroy this thing", @thing, method: :delete %>
</div>