config/routes.rb
Rails.application.routes.draw do
  resources :autocomplete_things
  resources :authors
  resources :dynamic_things
  resources :things
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/dynamic_thing.rb
class DynamicThing < ApplicationRecord
end

app/controllers/dynamic_things_controller.rb
class DynamicThingsController < ApplicationController
  before_action :set_dynamic_thing, only: %i[ show edit update destroy ]

  # GET /dynamic_things or /dynamic_things.json
  def index
    @dynamic_things = DynamicThing.all
  end

  # GET /dynamic_things/1 or /dynamic_things/1.json
  def show
  end

  # GET /dynamic_things/new
  def new
    @dynamic_thing = DynamicThing.new
  end

  # GET /dynamic_things/1/edit
  def edit
  end

  # POST /dynamic_things or /dynamic_things.json
  def create
    @dynamic_thing = DynamicThing.new(dynamic_thing_params)

    respond_to do |format|
      if @dynamic_thing.save
        format.html { redirect_to dynamic_thing_url(@dynamic_thing), notice: "Dynamic thing was successfully created." }
        format.json { render :show, status: :created, location: @dynamic_thing }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @dynamic_thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dynamic_things/1 or /dynamic_things/1.json
  def update
    respond_to do |format|
      if @dynamic_thing.update(dynamic_thing_params)
        format.html { redirect_to dynamic_thing_url(@dynamic_thing), notice: "Dynamic thing was successfully updated." }
        format.json { render :show, status: :ok, location: @dynamic_thing }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @dynamic_thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dynamic_things/1 or /dynamic_things/1.json
  def destroy
    @dynamic_thing.destroy

    respond_to do |format|
      format.html { redirect_to dynamic_things_url, notice: "Dynamic thing was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dynamic_thing
      @dynamic_thing = DynamicThing.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dynamic_thing_params
      params.require(:dynamic_thing).permit(:name, :active, :expiration_date)
    end
end

app/helpers/dynamic_things_helper.rb
module DynamicThingsHelper
end

app/views/dynamic_things/_dynamic_thing.html.erb
<div id="<%= dom_id dynamic_thing %>">
  <p>
    <strong>Name:</strong>
    <%= dynamic_thing.name %>
  </p>

  <p>
    <strong>Active:</strong>
    <%= dynamic_thing.active %>
  </p>

  <p>
    <strong>Expiration date:</strong>
    <%= dynamic_thing.expiration_date %>
  </p>

</div>

app/views/dynamic_things/_form.html.erb
<div data-controller="dynamic-datepicker" data-dynamic-datepicker-date-class="date">
<%= form_with(model: dynamic_thing) do |form| %>
  <% if dynamic_thing.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(dynamic_thing.errors.count, "error") %> prohibited this dynamic_thing from being saved:</h2>

      <ul>
        <% dynamic_thing.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :active, style: "display: block" %>
    <%= form.check_box :active %>
  </div>

  <div>
    <%= form.label :expiration_date, style: "display: block" %>
    <%= form.text_field :expiration_date, provide: "datepicker", class: "date" %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/dynamic_things/edit.html.erb
<h1>Editing dynamic thing</h1>

<%= render "form", dynamic_thing: @dynamic_thing %>

<br>

<div>
  <%= link_to "Show this dynamic thing", @dynamic_thing %> |
  <%= link_to "Back to dynamic things", dynamic_things_path %>
</div>

app/views/dynamic_things/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Dynamic things</h1>

<div id="dynamic_things">
  <% @dynamic_things.each do |dynamic_thing| %>
    <%= render dynamic_thing %>
    <p>
      <%= link_to "Show this dynamic thing", dynamic_thing %>
    </p>
  <% end %>
</div>

<div data-controller="dynamic-toggle" data-dynamic-toggle-toggle-class="hidden">
  <button data-action="dynamic-toggle#do_toggle">Hide/Show</button>
  <p data-dynamic-toggle-target="content">
    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna
    aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
    Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint
    occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
  </p>
</div>

<%= link_to "New dynamic thing", new_dynamic_thing_path %>

app/views/dynamic_things/new.html.erb
<h1>New dynamic thing</h1>

<%= render "form", dynamic_thing: @dynamic_thing %>

<br>

<div>
  <%= link_to "Back to dynamic things", dynamic_things_path %>
</div>

app/views/dynamic_things/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @dynamic_thing %>

<div>
  <%= link_to "Edit this dynamic thing", edit_dynamic_thing_path(@dynamic_thing) %> |
  <%= link_to "Back to dynamic things", dynamic_things_path %>

  <%= button_to "Destroy this dynamic thing", @dynamic_thing, method: :delete %>
</div>