config/routes.rb
Rails.application.routes.draw do
  resources :autocomplete_things
  resources :authors
  resources :dynamic_things
  resources :things
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/autocomplete_thing.rb
class AutocompleteThing < ApplicationRecord
  scope :name_search, ->(name) {where('name LIKE ?', "%#{sanitize_sql_like(name.present? ? name: '')}%")}
end

app/controllers/autocomplete_things_controller.rb
class AutocompleteThingsController < ApplicationController
  before_action :set_autocomplete_thing, only: %i[ show edit update destroy ]

  # GET /autocomplete_things or /autocomplete_things.json
  def index
    @autocomplete_things = AutocompleteThing.name_search(params[:name])
  end

  # GET /autocomplete_things/1 or /autocomplete_things/1.json
  def show
  end

  # GET /autocomplete_things/new
  def new
    @autocomplete_thing = AutocompleteThing.new
  end

  # GET /autocomplete_things/1/edit
  def edit
  end

  # POST /autocomplete_things or /autocomplete_things.json
  def create
    @autocomplete_thing = AutocompleteThing.new(autocomplete_thing_params)

    respond_to do |format|
      if @autocomplete_thing.save
        format.html { redirect_to autocomplete_thing_url(@autocomplete_thing), notice: "Autocomplete thing was successfully created." }
        format.json { render :show, status: :created, location: @autocomplete_thing }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @autocomplete_thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /autocomplete_things/1 or /autocomplete_things/1.json
  def update
    respond_to do |format|
      if @autocomplete_thing.update(autocomplete_thing_params)
        format.html { redirect_to autocomplete_thing_url(@autocomplete_thing), notice: "Autocomplete thing was successfully updated." }
        format.json { render :show, status: :ok, location: @autocomplete_thing }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @autocomplete_thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /autocomplete_things/1 or /autocomplete_things/1.json
  def destroy
    @autocomplete_thing.destroy

    respond_to do |format|
      format.html { redirect_to autocomplete_things_url, notice: "Autocomplete thing was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_autocomplete_thing
      @autocomplete_thing = AutocompleteThing.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def autocomplete_thing_params
      params.require(:autocomplete_thing).permit(:name, :random_field)
    end
end

app/helpers/autocomplete_things_helper.rb
module AutocompleteThingsHelper
end

app/views/autocomplete_things/_autocomplete_thing.html.erb
<div id="<%= dom_id autocomplete_thing %>">
  <p>
    <strong>Name:</strong>
    <%= highlight(autocomplete_thing.name, params[:name]) %>
  </p>

  <p>
    <strong>Random field:</strong>
    <%= autocomplete_thing.random_field %>
  </p>

</div>

app/views/autocomplete_things/_form.html.erb
<%= form_with(model: autocomplete_thing) do |form| %>
  <% if autocomplete_thing.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(autocomplete_thing.errors.count, "error") %> prohibited this autocomplete_thing from being saved:</h2>

      <ul>
        <% autocomplete_thing.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :random_field, style: "display: block" %>
    <%= form.text_field :random_field %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/autocomplete_things/edit.html.erb
<h1>Editing autocomplete thing</h1>

<%= render "form", autocomplete_thing: @autocomplete_thing %>

<br>

<div>
  <%= link_to "Show this autocomplete thing", @autocomplete_thing %> |
  <%= link_to "Back to autocomplete things", autocomplete_things_path %>
</div>

app/views/autocomplete_things/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Autocomplete things</h1>

<%= form_with url: autocomplete_things_path, method: :get, data: {'turbo-frame': 'autocomplete_things'} do |form| %>
  <% form.search_field :name, autofocus: true %>
<% end %>

<%= turbo_frame_tag :autocomplete_things do %>
  <div id="search-result">
    <%= pluralize(@autocomplete_things.count, 'autocomplete thing') %> found
  </div>

  <div id="autocomplete-things-container">
    <% @autocomplete_things.each do |autocomplete_thing| %>
      <%= render autocomplete_thing %>
      <p>
        <%= link_to "Show this autocomplete thing", autocomplete_thing %>
      </p>
    <% end %>
  </div>
<% end %>

<%= link_to "New autocomplete thing", new_autocomplete_thing_path %>

app/views/autocomplete_things/new.html.erb
<h1>New autocomplete thing</h1>

<%= render "form", autocomplete_thing: @autocomplete_thing %>

<br>

<div>
  <%= link_to "Back to autocomplete things", autocomplete_things_path %>
</div>

app/views/autocomplete_things/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @autocomplete_thing %>

<div>
  <%= link_to "Edit this autocomplete thing", edit_autocomplete_thing_path(@autocomplete_thing) %> |
  <%= link_to "Back to autocomplete things", autocomplete_things_path %>

  <%= button_to "Destroy this autocomplete thing", @autocomplete_thing, method: :delete %>
</div>